      
#################################################################################
## COLLECTIONS : DISPLAY OF COLLECTIONS By CONTROLLER 
splash_widgets_demo_home:
    path:     /
    defaults: { _controller: Splash\Widgets\Controller\DemoController::collectionAction }

splash_widgets_demo_collection:
    path:     /collection
    defaults: { _controller: Splash\Widgets\Controller\DemoController::collectionAction }
    
splash_widgets_demo_collection_edit:
    path:     /collection/edit
    defaults: { _controller: Splash\Widgets\Controller\DemoController::collectionEditAction }


#################################################################################
## LIST : DISPLAY LIST OF AVAILABLE WIDGETS
splash_widgets_demo_list:
    path:     /list
    defaults: { _controller: Splash\Widgets\Controller\DemoController::listAction }

#################################################################################
## WIDGETS : DISPLAY OF WIDGETS By CONTROLLER
splash_widgets_demo_single_forced:
    path:     /forced
    defaults: { _controller: Splash\Widgets\Controller\DemoController::forcedAction }

splash_widgets_demo_single_delayed:
    path:     /delayed
    defaults: { _controller: Splash\Widgets\Controller\DemoController::delayedAction }

splash_widgets_demo_single_edit:
    path:     /edit/{widgetType}
    defaults:
        _controller: Splash\Widgets\Controller\DemoController::editAction
        widgetType: Text

#################################################################################
## WIDGETS : DISPLAY OF WIDGETS By SONATA BLOCKS 
splash_widgets_demo_blocks:
    path:           /blocks
    controller:     Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template:   "@SplashWidgets/Demo/Blocks/index.html.twig"
        
splash_widgets_demo_single_blocks:
    path:           /single/blocks
    controller:     Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template:   "@SplashWidgets/Demo/Blocks/single.html.twig"

#################################################################################
## DEBUG
splash_widgets_demo_debug:
    path:           /debug/{Service}/{Type}
    controller:     Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template:   "@SplashWidgets/Demo/Debug/index.html.twig"
                