# Doctrine Configuration
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                url: '%env(resolve:DATABASE_URL)%'

#    dbal:
#        driver: 'pdo_sqlite'
#        path: '%kernel.project_dir%/var/data.db'

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true