


splash_widgets_render:
    path:     /view/{Service}/{Type}/{Edit}
    defaults: 
        _controller:    SplashWidgetsBundle:View:ajax
        Edit:           false
    options:
        expose: true
        
#################################################################################
## WIDGET : AJAX EDIT MODAL
splash_widgets_edit:
    path:     /edit/{Service}/{Type}
    defaults: 
        _controller: SplashWidgetsBundle:Edit:modal
    options:
        expose: true
        
#################################################################################
## COLLECTIONS : AJAX ORDERING UPDATE
splash_widgets_ajax_reorder:
    path:     /reorder/{CollectionId}/{Ordering}
    defaults: { _controller: SplashWidgetsBundle:Collection:reorder }
    options:
        expose: true 
        
#################################################################################
## COLLECTIONS : AJAX ADD WIDGET
splash_widgets_ajax_add:
    path:     /add/{CollectionId}/{Service}/{Type}
    defaults: { _controller: SplashWidgetsBundle:Collection:add }
    options:
        expose: true    
        
#################################################################################
## COLLECTIONS : AJAX REMOVE WIDGET
splash_widgets_ajax_remove:
    path:     /remove/{Service}/{Type}
    defaults: { _controller: SplashWidgetsBundle:Collection:remove }
    options:
        expose: true          
        
#################################################################################
## COLLECTIONS : AJAX WIDGET LIST MODAL
splash_widgets_ajax_list:
    path:     /list/{CollectionId}/{Channel}
    defaults: { _controller: SplashWidgetsBundle:List:modal }
    options:
        expose: true         