


splash_widgets_render:
    path:     /view/{Service}/{WidgetId}/{Options}/{Parameters}
    defaults: 
        _controller: SplashWidgetsBundle:View:ajax
        Options:    null
        Parameters: null
    options:
        expose: true

splash_widgets_demo:
    path:     /demo
    defaults: { _controller: SplashWidgetsBundle:Demo:index }