#################################################################################
## WIDGET : AJAX RENDER
splash_widgets_render_widget:
    path:     /view/{Service}/{Type}/{Edit}/{Editable}
    defaults: 
        _controller:    SplashWidgetsBundle:View:ajax
        Edit:           false
        Editable:       false
    options:
        expose: true
        
#################################################################################
## WIDGET : AJAX EDIT MODAL
splash_widgets_edit_widget:
    path:     /edit/{Service}/{Type}
    defaults: 
        _controller: SplashWidgetsBundle:Edit:modal
    options:
        expose: true
        
#################################################################################
## COLLECTIONS : AJAX ORDERING UPDATE
splash_widgets_collections_reorder:
    path:     /reorder/{CollectionId}/{Ordering}
    defaults: { _controller: SplashWidgetsBundle:Collection:reorder }
    options:
        expose: true
        
#################################################################################
## COLLECTIONS : AJAX DATE PRESET UPDATE
splash_widgets_collections_preset:
    path:     /preset/{CollectionId}/{Preset}
    defaults: { _controller: SplashWidgetsBundle:Collection:preset }
    options:
        expose: true 
        
#################################################################################
## COLLECTIONS : AJAX ADD WIDGET
splash_widgets_collections_add_widget:
    path:     /add/{CollectionId}/{Service}/{Type}
    defaults: { _controller: SplashWidgetsBundle:Collection:add }
    options:
        expose: true    
        
#################################################################################
## COLLECTIONS : AJAX REMOVE WIDGET
splash_widgets_collections_remove_widget:
    path:     /remove/{Service}/{Type}
    defaults: { _controller: SplashWidgetsBundle:Collection:remove }
    options:
        expose: true          
        
#################################################################################
## COLLECTIONS : AJAX WIDGETS LIST MODAL
splash_widgets_collections_list_widget:
    path:     /list/{CollectionId}/{Channel}
    defaults: { _controller: SplashWidgetsBundle:List:modal }
    options:
        expose: true          