################################################################################
#
#  This file is part of SplashSync Project.
#
#  Copyright (C) Splash Sync <www.splashsync.com>
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
#  For the full copyright and license information, please view the LICENSE
#  file that was distributed with this source code.
#
#  @author Bernard Paquier <contact@splashsync.com>
#
################################################################################

################################################################
# Set any variables we need
variables:
  MYSQL_DATABASE:               symfony
  MYSQL_ROOT_PASSWORD:          Widgets-Bundle
  COMPOSER_MEMORY_LIMIT:        -1
  SYMFONY_DEPRECATIONS_HELPER:  disabled

################################################################
# Configure Services
services:
  - mariadb

################################################################
# Defined Pipeline Stages
stages:
  - Symfony-5
  - Symfony-6
  - Symfony-7
#  - Builds


################################################################
# Functional Tests
################################################################

.core_tests:    &core_tests
    stage:      tests
    tags:
        - Dedicated
    artifacts:
        when: always
        reports:
            junit: "$CI_PROJECT_DIR/*-report.xml"
    ################################################################################
    # Install & Configure Environment
    before_script:
        # Setup Travis
        - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/ci/configure.sh  | sh
        # Deploy Symfony Files
        - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/symfony/deploy.sh | sh
        # Setup Symfony Version & Create Database
        - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/symfony/configure.sh | sh
        # Install Symfony
        - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/symfony/install.sh | sh

    ################################################################################
    # Run Test Script
    script:
        # Execute Grumphp Testsuite
        - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/ci/grumphp.sh  | sh
        # Execute PhpUnit Tests
        - vendor/bin/phpunit --log-junit $CI_PROJECT_DIR/test-report.xml

    ################################################################################
    # Run After Script
    after_script:
      - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/ci/after.sh | sh

################################################################
# Symfony 7
################################################################

sf7:php-8.3:
    <<: *core_tests
    stage:            Symfony-7
    image:            registry.gitlab.com/badpixxel-projects/php-sdk:php-8.3
    variables:
        SYMFONY_REQUIRE: 7.*

sf7:php-8.2:
    <<: *core_tests
    stage:            Symfony-7
    image:            registry.gitlab.com/badpixxel-projects/php-sdk:php-8.2
    variables:
        SYMFONY_REQUIRE: 7.*

sf7:php-8.1:
    <<: *core_tests
    stage:            Symfony-7
    image:            registry.gitlab.com/badpixxel-projects/php-sdk:php-8.1
    variables:
        SYMFONY_REQUIRE: 7.*

################################################################
# Symfony 6
################################################################

sf6:php-8.3:
    <<: *core_tests
    stage:            Symfony-6
    image:            registry.gitlab.com/badpixxel-projects/php-sdk:php-8.3
    variables:
        SYMFONY_REQUIRE: 6.4.*

sf6:php-8.2:
    <<: *core_tests
    stage:            Symfony-6
    image:            registry.gitlab.com/badpixxel-projects/php-sdk:php-8.2
    variables:
        SYMFONY_REQUIRE: 6.4.*

sf6:php-8.1:
    <<: *core_tests
    stage:            Symfony-6
    image:            registry.gitlab.com/badpixxel-projects/php-sdk:php-8.1
    variables:
        SYMFONY_REQUIRE: 6.4.*

################################################################
# Symfony 5
################################################################

#sf5:php-8.2:
#    <<: *core_tests
#    stage:            Symfony-5
#    image:            registry.gitlab.com/badpixxel-projects/php-sdk:php-8.2
#    variables:
#        SYMFONY_REQUIRE: 5.4.*
#
#sf5:php-8.1:
#    <<: *core_tests
#    stage:            Symfony-5
#    image:            registry.gitlab.com/badpixxel-projects/php-sdk:php-8.1
#    variables:
#        SYMFONY_REQUIRE: 5.4.*



################################################################
# Build Documentation
################################################################
#pages:
#    image:    registry.gitlab.com/badpixxel-projects/php-sdk:jekyll
#    stage:    deploy
#    tags:
#      - Dedicated
#    services:
#      - docker:dind
#    ################################################################################
#    # Run Test Script
#    script:
#      # Deploy Symfony Files
#      - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/symfony/deploy.sh | sh
#      # Run Composer to Build deps
#      - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/ci/composer.sh  | bash
#      # Build Documentation
#      - php vendor/bin/grumphp run --tasks=build-docs
#    artifacts:
#        paths:
#            - public
