# Project language
language: php

# Allows use container-based infrastructure
sudo: false
#sudo: required
dist: trusty

# Start mysql service
services:
  - mysql

# Cache composer packages so "composer install" is faster
cache:
    directories:
        - $HOME/.composer/cache/files

# Define an environment variable
env:
    global:
        - SYMFONY_DEPRECATIONS_HELPER=disabled
        
# Define Test Matrix
matrix:
    include:     
          
#        # Symfony 3.3 Branch       
#        - php: 7.0
#          env: SF_VERSION="3.3.*"        
#        - php: 7.1
#          env: SF_VERSION="3.3.*"        
          
        # Symfony 3.4 Branch       
#        - php: 7.1
#          env: SF_VERSION="3.4.*"        
        - php: 7.2
          env: SF_VERSION="3.4.*"        
          
#        # Symfony 4.0 Branch       
#        - php: 7.1
#          env: SF_VERSION="4.0.*"  STABILITY="dev"   
#        - php: 7.2
#          env: SF_VERSION="4.0.*"  STABILITY="dev"        
        
    allow_failures:
        - env: SF_VERSION="4.0.*"  STABILITY="dev"       
        
    # Fast finish allows to set the build as "finished" even if the "allow_failures" matrix elements are not finished yet.
    fast_finish: true

before_script:
    - phpenv config-rm xdebug.ini
  
# Install composer dependencies,
# Create database, schema and fixtures
install:   
    # Copy Parameters
    - echo "Configuring The Bundles"
    - cp app/parameters.yml.dist app/parameters.yml
    # Setup Travis
    - curl -s https://raw.githubusercontent.com/SplashSync/Php-Bundle/master/src/Resources/travis/configure.sh  | bash
    # Setup Symfony Version if Required
    - curl -s https://raw.githubusercontent.com/SplashSync/Php-Bundle/master/src/Resources/travis/build_symfony.sh  | bash
    # Configure For Phpstan vs PHP Versions
    - curl -s https://raw.githubusercontent.com/SplashSync/Php-Bundle/master/src/Resources/travis/build_grumphp.sh  | bash
    # Install Symfony
    - curl -s https://raw.githubusercontent.com/SplashSync/Php-Bundle/master/src/Resources/travis/install.sh  | bash      
    # Copy Assets
    - echo "Dump & Install Assets"
    - php bin/console assetic:dump --no-interaction --no-debug

# Run script
script:
    - phpunit

# After a build, send email notification with the build results
#notifications:
#  email: your_email