################################################################################
# Define Test Matrix
matrix:
    include:     
          
        # Symfony 3.4 Branch       
        - php: 7.2
          env: SF_VERSION="3.4.*"        
        - php: 7.3
          env: SF_VERSION="3.4.*"        
          
        # Symfony 4.2 Branch       
        - php: 7.3
          env: SF_VERSION="4.2.*"   
        
    allow_failures:
        - env: SF_VERSION="4.2.*"
        
    # Fast finish allows to set the build as "finished" even if the "allow_failures" matrix elements are not finished yet.
    fast_finish: true

before_script:
    - phpenv config-rm xdebug.ini
  
# Install composer dependencies,
# Create database, schema and fixtures
install:   
    # Copy Parameters
    - echo "Configuring The Bundles"
    - cp app/parameters.yml.dist app/parameters.yml
    # Setup Travis
    - curl -s https://raw.githubusercontent.com/SplashSync/Php-Bundle/master/src/Resources/travis/configure.sh  | bash
    # Setup Symfony Version if Required
    - curl -s https://raw.githubusercontent.com/SplashSync/Php-Bundle/master/src/Resources/travis/build_symfony.sh  | bash
    # Configure For Phpstan vs PHP Versions
    - curl -s https://raw.githubusercontent.com/SplashSync/Php-Bundle/master/src/Resources/travis/build_grumphp.sh  | bash
    # Install Symfony
    - curl -s https://raw.githubusercontent.com/SplashSync/Php-Bundle/master/src/Resources/travis/install.sh  | bash      

# Run script
script:
    # Execute Grump Testsuites 
    - php vendor/bin/grumphp run --testsuite=travis
    - php vendor/bin/grumphp run --testsuite=csfixer
    - php vendor/bin/grumphp run --testsuite=phpstan
    # Execute Fuctionnal Testsuites 
    - php vendor/bin/phpunit

################################################################################
# Project language
language: php
# Allows use container-based infrastructure
sudo: false
#sudo: required
dist: trusty
################################################################################
# Start mysql service
services:
  - mysql
################################################################################
# Cache composer packages so "composer install" is faster
cache:
    directories:
        - $HOME/.composer/cache/files
################################################################################
# Define an environment variable
env:
    global:
        - SYMFONY_DEPRECATIONS_HELPER=disabled
################################################################################
# After a build, send email notification with the build results
notifications:
  email:         
    on_success: never # default: change
    on_failure: never # default: always