################################################################################
#
#  This file is part of SplashSync Project.
# 
#  Copyright (C) Splash Sync <www.splashsync.com>
# 
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# 
#  For the full copyright and license information, please view the LICENSE
#  file that was distributed with this source code.
# 
#  @author Bernard Paquier <contact@splashsync.com>
#
################################################################################

################################################################################
# Docker Compose File
#
# This Docker File intend to Create a Complete Widget Environment
# for Development or Tests of Widget Bundle
#
# You can to add host to /etc/hosts
# 
# 172.205.1.10          app.widgets.local
# 172.205.1.74          74.widgets.local
# 172.205.1.64          64.widgets.local
# 172.205.1.54          54.widgets.local
# 172.205.1.100         db.widgets.local
# 172.205.1.200         phpmyadmin.widgets.local
#
################################################################################

services:

    ################################################################################
    # Develop Image
    app:
        image:          "registry.gitlab.com/badpixxel-projects/php-sdk:php-8.3"
        container_name: app.widgets.local
        hostname:       app.widgets.local
        environment:
            SERVER_ROOT: /var/www/html/tests/public
        volumes:
            - ./:/var/www/html/
        networks:
            default: { ipv4_address: 172.205.1.10, aliases: [ app.widgets.local ] }

    ################################################################################
    # Symfony 7 + PHP 8.3
    sf7:
        image:          "registry.gitlab.com/badpixxel-projects/php-sdk:php-8.3"
        container_name: sf7.widgets.local
        hostname:       sf7.widgets.local
        volumes:
            - ./:/var/www/html
            - sf7-var:/var/www/html/var
            - sf7-vendor:/var/www/html/vendor
        environment:
            SERVER_ROOT: /var/www/html/tests/public
            SYMFONY_REQUIRE: 7.*
        networks:
            default: { ipv4_address: 172.205.1.74, aliases: [ sf7.widgets.local ] }

    ################################################################################
    # Symfony 6 + PHP 8.2
    sf6:
        image:          "registry.gitlab.com/badpixxel-projects/php-sdk:php-8.2"
        container_name: sf6.widgets.local
        hostname:       sf6.widgets.local
        volumes:
            - ./:/var/www/html
            - sf6-var:/var/www/html/var
            - sf6-vendor:/var/www/html/vendor
        environment:
            SERVER_ROOT: /var/www/html/tests/public
            SYMFONY_REQUIRE: 6.4.*
        networks:
            default: { ipv4_address: 172.205.1.64, aliases: [ sf6.widgets.local ] }

    ################################################################################
    # Symfony 6 + PHP 8.2
    sf5:
        image:          "registry.gitlab.com/badpixxel-projects/php-sdk:php-8.1"
        command:        sh /var/www/html/docker/docker-entrypoint.sh
        container_name: sf5.widgets.local
        hostname:       sf5.widgets.local
        volumes:
            - ./:/var/www/html
            - ./docker/sites-available/000-default.conf:/etc/apache2/sites-available/000-default.conf
            - sf5-var:/var/www/html/var
            - sf5-vendor:/var/www/html/vendor
        environment:
            SYMFONY_REQUIRE: 5.4.*
        networks:
            default: { ipv4_address: 172.205.1.54, aliases: [ sf5.widgets.local ] }

volumes:
    sf7-var:        ~
    sf7-vendor:     ~
    sf6-var:        ~
    sf6-vendor:     ~
    sf5-var:        ~
    sf5-vendor:     ~

networks:
    ################################################################################
    # Default Private Network
    default:
        driver: bridge
        ipam:
            config:
                - subnet: 172.205.1.0/24
