################################################################################
# Symfony WebProfiler Routes
_wdt:
    resource:   "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:     /_wdt

################################################################################
# Symfony Profiler Routes
_profiler:
    resource:   "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:     /_profiler    