# Doctrine Configuration
doctrine:
    dbal:
        driver: 'pdo_sqlite'
        path: '%kernel.project_dir%/var/data.db'

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true