
################################################################################
# DEBUG TOOLBAR Configuration & Profiling
################################################################################     

framework:
   profiler: { only_exceptions: false }

web_profiler:
    toolbar:             true
    intercept_redirects: false
    excluded_ajax_paths:  ^/bundles|^/_wdt
