sonata_block:
    blocks:        
        splash.widgets.blocks.collection:
            contexts:   [admin]
        splash.widgets.blocks.simple:
            contexts:   [admin]
        
services:

    #################################################################################
    # Widgets Collection Sonata Block Service
    splash.widgets.blocks.collection:
        class: Splash\Widgets\Block\WidgetCollectionBlock
        arguments:
            - "splash.widgets.blocks.collection"
            - "@templating"
            - "@doctrine.orm.entity_manager"
            - "@request_stack"
        tags:
            - { name: sonata.block }
            
    #################################################################################
    # Single Widget Sonata Block Service
    splash.widgets.blocks.simple:
        class: Splash\Widgets\Block\WidgetBlock
        arguments:
            - "splash.widgets.blocks.simple"
            - "@templating"
            - "@splash.widgets.manager"
            - "@splash.widgets.factory"
        tags:
            - { name: sonata.block } 
