services:
    _defaults:
        autowire: true

    #################################################################################
    # Widgets Collection Sonata Block Service
    splash.widgets.blocks.collection:
        class: Splash\Widgets\Block\WidgetCollectionBlock
        tags:
            - { name: sonata.block }

    #################################################################################
    # Single Widget Sonata Block Service
    splash.widgets.blocks.simple:
        class: Splash\Widgets\Block\WidgetBlock
        tags:
            - { name: sonata.block }
