services:

    # Demo Widgets Factory Service
    splash.widgets.demo.factory:
        class:      Splash\Widgets\Services\Demo\SamplesFactoryService
        arguments:  ["@splash.widgets.factory"]
        public:     true
        tags:
            - { name: kernel.event_listener, event: Splash\Widgets\Event\ListingEvent, method: onListingAction }

