services:

    # Demo Widgets Factroy Service
    splash.widgets.demo.factory:
        class: Splash\Widgets\Services\Demo\SamplesFactoryService
        arguments: ["@splash.widgets.factory"]             
        tags:
            - { name: kernel.event_listener, event: splash.widgets.list.demo, method: onListingAction }

