services:

    _defaults:
        autowire: true

    ################################################################################
    # AutoWire for Controllers
    Splash\Widgets\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']


    # Widget Parser & Creation Service
    splash.widgets.factory:
        class:      Splash\Widgets\Services\FactoryService
        public:     true

    # Widgets Manager Service
    splash.widgets.manager:
        class:      Splash\Widgets\Services\ManagerService
        public:     true

    # Widgets Collection Service
    splash.widgets.collection:
        class:      Splash\Widgets\Services\CollectionService
        public:     true

    # Auto Wiring
    Splash\Widgets\Services\FactoryService:     "@splash.widgets.factory"
    Splash\Widgets\Services\ManagerService:     "@splash.widgets.manager"
    Splash\Widgets\Services\CollectionService:  "@splash.widgets.collection"
