imports:
    - { resource: parameters.yml }
    - { resource: config/framework.yml }
    - { resource: config/doctrine.yml }
    - { resource: config/twig.yml }
    - { resource: config/webpack_encore.yml }
    - { resource: "@SplashWidgetsBundle/Resources/config/blocks.yml" }
    - { resource: "@SplashWidgetsBundle/Resources/config/demo.yml" }
    
# Debug Toolbar    
#web_profiler:
#    toolbar:             true
    