imports:
    - { resource: config.yml }
    - { resource: "@SplashWidgetsBundle/Resources/config/test.yml" }
    
# Framework Configuration
framework:
    test: ~
    router:
        resource:   "%kernel.root_dir%/routing_test.yml"
    session:
        storage_id: session.storage.filesystem
        
# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: true

# WebPack Encore 
webpack_encore:
    # Throw an exception if the entrypoints.json file is missing or an entry is missing from the data
    strict_mode: false