imports:
    - { resource: config.yml }
    - { resource: "@SplashWidgetsBundle/Resources/config/test.yml" }
    
# Framework Configuration
framework:
    router:
        resource:   "%kernel.root_dir%/routing_test.yml"
    
# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: true

    