imports:
    - { resource: parameters.yml }
    - { resource: "@SplashWidgetsBundle/Resources/config/blocks.yml" }
    - { resource: "@SplashWidgetsBundle/Resources/config/demo.yml" }
    
    
# Framework Configuration
framework:
    translator:      { fallbacks: ["%locale%"] }
    router:
        resource: "routing.yml"
    templating:
        engines: ['twig']  
    form:           ~
    session:        ~    
       

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

mopa_bootstrap:
    menu: ~
    form: ~
    
#twig:
#    form_themes:
#    -   "@MopaBootstrap/Form/fields.html.twig"
    