
################################################################################
# SPLASH Widget Bundle Core Routes
splash_widgets_bundle_core:
    resource: "@SplashWidgetsBundle/Resources/config/routing.yml"
    prefix:   /  
    
################################################################################
# SPLASH Widget Bundle Demo Routes
splash_widgets_bundle_demo:
    resource: "@SplashWidgetsBundle/Resources/config/routing/demo.yml"
    prefix:   /  
    
################################################################################
# Symfony WebProfiler Routes
_wdt:
    resource:   "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:     /_wdt

################################################################################
# Symfony Profiler Routes
_profiler:
    resource:   "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:     /_profiler    