#################################################################################
## WIDGET : AJAX RENDERING
splash_widgets_render_widget:
    path:     /view/{Service}/{Type}/{Edit}
    defaults: 
        _controller:    SplashWidgetsBundle:View:ajax
        Edit:           false
    options:
        expose: true
        
#################################################################################
## WIDGET : AJAX EDIT MODAL
splash_widgets_edit_widget:
    path:     /edit/{Service}/{Type}
    defaults: 
        _controller: SplashWidgetsBundle:Edit:modal
    options:
        expose: true
               
               